### ISSUE TITLE
tabry-generate-bash-complete doesn't read flagargs

### ISSUE THREAD

**Issue by pfgray** [evanbattaglia/tabry#7]
I suspect this has something to do with the `Tabry::CLI::AllInOne` helper, but both the `uniq_function_id` and `ruby_path` flagargs ([here](https://github.com/evanbattaglia/tabry/blob/master/bin/tabry-generate-bash-complete#L27)) are ignored when running `tabry-generate-bash-complete`.

When I log them out, they are empty strings, so they don't get defaulted as specified here: https://github.com/evanbattaglia/tabry/blob/master/lib/tabry/shells/bash.rb#L17

**Comment by evanbattaglia** [comment]
Sorry about that. Fixed the ruby flag. Can you please try again? The uniq_fn_id was always working for me.

```
$ bin/tabry-generate-bash-complete mycli foo.json -r myruby -i $ bin/tabry-generate-bash-complete mycli foo.json -r myruby -i UNIQID|grep UNIQID
_tabry_UNIQID_completions() {
...
```
